### ISSUE TITLE
Error : kohii.setUp(url).bind(playerView) class file for kotlin.jvm.functions.Function1 not found

### ISSUE THREAD

**Issue by nirazv** [eneim/kohii#101]
I am getting compile time error while using Kohii with Java

kohii.setUp(url).bind(playerView) class file for kotlin.jvm.functions.Function1 not found

My Code

` container = findViewById(R.id.container);
    playerView = findViewById(R.id.playerView);
    Kohii kohii = Kohii.get(this);
    kohii.register(this).addBucket(container);
    kohii.setUp(url).bind(playerView);`

**Comment by eneim** [comment]
@nirazv Can you take a look at this SO link and double check your compiler setting and Kotlin versions?

https://stackoverflow.com/questions/35161913/kotlin-cannot-access-kotlin-jvm-functions-function1-when-calling-kotlin-function/55742956

**Comment by eneim** [comment]
Also post my answer here:

https://stackoverflow.com/a/63884465/1553254
