### ISSUE TITLE
Kohii is playing video in background.

### ISSUE THREAD

**Issue by deepanshut041** [eneim/kohii#107]
I'm using kohii inside fragment in recyclerview. I have bottom navigation activity in which I'm using .show() and .hide() to change fragment.

## Current behavior: 
Video is playing on hide fragment.

## Expected behavior:
Video must pause on hide fragment and resume on show fragment.

**Comment by eneim** [comment]
@deepanshut041 I guess Kohii cannot judge if the Fragment View is detached. Please try `kohii.lockManager(fragment)` (API: https://github.com/eneim/kohii/blob/bb096fd2f5176f4c180783422918dff81f7c8142/kohii-core/src/main/java/kohii/v1/core/Engine.kt#L201) to lock all possible playbacks in a Fragment, and use `kohii.unlockManager(fragment)` to unlock it.

**Comment by deepanshut041** [comment]
@eneim thanks below solution worked for me 

```java
override fun onHiddenChanged(hidden: Boolean) {
    super.onHiddenChanged(hidden)
    if (hidden) {
        kohii.lockBucket(this.recyclerView);
    } else {
        kohii.unlockBucket(this.recyclerView);
    }
}
```
