### ISSUE TITLE
Video playback does not resume after screen was turned off and on quickly

### ISSUE THREAD

**Issue by jsadovskaya** [eneim/kohii#114]
Hi! thanks for your library, it's very helpful!

I faced an issue with resuming video playback after device screen was turned off and then turned on again. The video playback is staying locked and doesn't resume. It's reproducing stably when I do it quite quickly (on real devices and emulators). 

I made some investigations:
- I found screenStateReceiver in Master.kt that handles system intents and updates systemLock property which affects the video playback  
- I added some logs to check what intents are received inside it 

And here is what I found:
- in default case when I turn off the device screen and then turn it on after a while everything works correctly - firstly SCREEN_OFF intent is received and handled(systemLock -> true) and secondly USER_PRESENT intent is received and handled (systemLock -> false) 
- in case when I turn off the device screen and then turn it on quite quickly or when I make double power button press (on some devices, Pixel 3, for example, this action can be set as camera starting) - the received intents order is different - firstly USER_PRESENT intent is received, after it SCREEN_OFF is received, and then SCREEN_ON is received, but it doesn't have any handling. So in this case the systemLock stays "true" and prevents video resuming even though the screen is on.

<img width="918" alt="Снимок экрана 2020-11-02 в 23 06 47" src="https://user-images.githubusercontent.com/16334217/97913960-2b923480-1d60-11eb-8ca2-a7c1cfbc4544.png">

Would be glad if you check these cases and help me with this issue.

**Comment by eneim** [comment]
@jsadovskaya Sorry for the late reply and really thanks for the investigation. Please allow me some days to look into the issue and deliver a fix. I believe a simple change in the way of handling the Intent would fix it.
