### ISSUE TITLE
Pre-Caching videos with Kohii

### ISSUE THREAD

**Issue by arsalrao** [eneim/kohii#134]
@eneim is there any way to use pre-cache in Kohii?  I found this https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6 but how can I use **CacheUtil** in kohii.

**Background:**
I'm working on a short video social platform so I need to cache upcoming videos for a better user experience.

Thanks.

**Comment by eneim** [comment]
@arsalrao CacheUtil is not useful in Kohii. For you scenario, can you take a look at this sample: https://github.com/eneim/kohii/blob/0d579c2d34ebeba26fee2f3bff13f785c8c92047/kohii-sample-tiktok/

In short, it customizes the loading spec of ExoPlayer so your Video will start early and it also caches what it loads already (it is a LRU Cache with a configurable cache size, so it would not cache everything, but should be enough for short Videos). Didn't have enough time to really carefully test for offline playback of already-cached Videos, but it should be working I suppose.

**Comment by arsalrao** [comment]
@eneim I'm using it already but it didn't meet our expectations. For now, I'm closing this as you said CacheUtil is not useful in kohii

**Comment by eneim** [comment]
Thanks @arsalrao . If you still want to consider using Kohii, you can start a discussion with your expectation and I can think about that. One of the TODO I have for me is to better support cold pre fetch Video (i.e. pre loading Video without the UI work. The challenge is how you sync the pre-loaded Video with the setup in UI layer).

**Comment by arsalrao** [comment]
@eneim Thank you, you have TODO about the cold prefetch Video.  My expectation has the same but only buffered some chunks of videos before playing to make video streaming smooth fast like other social platform Tiktok doing.

**Comment by rahul-sysquare** [comment]
> Thanks @arsalrao . If you still want to consider using Kohii, you can start a discussion with your expectation and I can think about that. One of the TODO I have for me is to better support cold pre fetch Video (i.e. pre loading Video without the UI work. The challenge is how you sync the pre-loaded Video with the setup in UI layer).

I'm also looking for the same thing is it done already?

**Comment by rahul-sysquare** [comment]
@arsalrao  @eneim What is the preferred way for this (cold pre fetch Video)?
