### ISSUE TITLE
1.3.0.2011008-20210429.080049-18 is not found at Sonatype

### ISSUE THREAD

**Issue by hantrungkien** [eneim/kohii#166]
We're using this version for our product but at yesterday, we can't get this version from Sonatype. It seems to have been deleted.  Please help me. Thanks!

https://github.com/eneim/kohii/issues/112#issuecomment-756113102

```
    object Kohii {
        // https://oss.sonatype.org/content/repositories/snapshots/im/ene/kohii/
        const val core = "im.ene.kohii:kohii-core:1.3.0.2011008-20210429.080049-18"
        const val exoPlayer = "im.ene.kohii:kohii-exoplayer:1.3.0.2011008-20210330.004840-9"
    }
```

**Comment by eneim** [comment]
@hantrungkien Sorry for the inconvenience, can you try again using `1.3.0.2011008-20210611.055203-10`?

**Comment by hantrungkien** [comment]
@eneim is "kohii-core-1.3.0.2011008-20210611.055203-22" correct version? Please confirm for me is it built with the source code of 1.3.0.2011008-20210429.080049-18?

I have decided to using your awesome lib for the leading social networks at Vietnam are Gapo and Gapo Work so could you please publish this version on maven or jitpack repository to support me?

**Comment by eneim** [comment]
@hantrungkien The exact version of `kohii-core` and `kohii-exoplayer` are different:

https://oss.sonatype.org/content/repositories/snapshots/im/ene/kohii/kohii-core/1.3.0.2011008-SNAPSHOT/ --> `kohii-core-1.3.0.2011008-20210611.055203-22`
https://oss.sonatype.org/content/repositories/snapshots/im/ene/kohii/kohii-exoplayer/1.3.0.2011008-SNAPSHOT/ --> `kohii-exoplayer-1.3.0.2011008-20210611.055203-10`

But they are built from the same source code as what you had before. The following setup should work well:

```groovy
implementation("im.ene.kohii:kohii-core:1.3.0.2011008-20210611.055203-22") // core library
implementation("im.ene.kohii:kohii-exoplayer:1.3.0.2011008-20210611.055203-10") // default support for ExoPlayer
implementation("com.google.android.exoplayer:exoplayer:2.11.8") // required ExoPlayer implementation.
```

And these binaries will not be removed from SNAPSHOT repository. For all modules, please check this link: https://oss.sonatype.org/content/repositories/snapshots/im/ene/kohii/

**Comment by hantrungkien** [comment]
@eneim thanks bro!

**Comment by hantrungkien** [comment]
@eneim I have got a conflict with other lib using exoplayer 2.13.3 so could you please push this version on git?

**Comment by hantrungkien** [comment]
@eneim Could you please support me?
