### ISSUE TITLE
Video player blinks in RecyclerView

### ISSUE THREAD

**Issue by sdex** [eneim/kohii#167]
Hi Nam.

I'm trying to use your awesome library to play videos in RecyclerView in a way very similar to the sample `Kohii + Facebook`. 
The issue I've faced is that when scrolling between videos the player view becomes kind of invisible for a moment instead of displaying the last video frame.

The video demonstrates this issue:
https://user-images.githubusercontent.com/3196011/122721264-20e9c880-d279-11eb-98e2-3ec077844298.mp4

I created a minimum reproducible sample that also demonstrates it:
https://github.com/sdex/kohii/commit/5d8b6c8bef5df8b18a94a2063521e175a34ba765

Because of this blink, the playback is not smooth, so I wonder how it can be improved.
I believe I configured it for the best performance, I use `ExoPlayerConfig.FAST_START`, `MemoryMode.HIGH`, preloading is enabled, and `keep_content_on_player_reset` is set to true. 
Do you have any idea how the playback can be improved?

**Comment by eneim** [comment]
@sdex Sorry for not checking this issue. Want to confirm the issue: the "blink" you mention is a short time when the screen turns white? I believe it is because you are reusing the PlayerView instance. And because the PlayerView instance is reused, the `keep_content_on_player_reset` setting doesn't take effect.

If you can trade-off the memory usage to get better performance, you can replace your container (which is not a PlayerView I believe) with a PlayerView. That way, the PlayerView will not be replaced (unless it is recycled by RecyclerView of course).

Please try this and let me know if it solves your issue.

**Comment by sdex** [comment]
@eneim correct, white screen instead of the last visible frame.
Not sure what exactly I need to replace with `PlayerView`. I have a list item view with the structure:
```
LinearLayout
  ConstraintLayout
    PlayerView
```
And in the view holder I do:
```
kohii.setUp(mediaLink).bind(playerView)
```

After all, we came up with listening to the player events and displaying a thumbnail when playback is not started yet.
It's not a perfect solution but it minimizes UI lags during scrolling.

**Comment by eneim** [comment]
@sdex 

> Not sure what exactly I need to replace with PlayerView.

Yeah, your current structure would be what I recommend. I also acknowledge your concern now: by default, there is nothing shown in the PlayerView if the video is not playing (for example, before the beginning of the playback, during the buffering for the first playback, after the playback has ended) which cause the UI to look weird (black screen, or white, ...).

I think the approach that uses player events to show/hide the thumbnail is reasonable. There is `ArtworkHintListener`  interface you can set when calling `kohii.setUp`, you can try that and see if it helps your case as well.

**Comment by sdex** [comment]
@eneim eventually we got what we needed listening events from different callbacks:
`Playback.StateListener`, `Playback.ArtworkHintListener`, `Player.Listener`
Based on the event and the player state we either show or hide the thumbnail and the controller.

**Comment by rahul-sysquare** [comment]
> @eneim eventually we got what we needed listening events from different callbacks: `Playback.StateListener`, `Playback.ArtworkHintListener`, `Player.Listener` Based on the event and the player state we either show or hide the thumbnail and the controller.

Do you have any idea like when we hide thumbnail how we can start video from beginning?
