### ISSUE TITLE
How to stop video playback when the app goes to background

### ISSUE THREAD

**Issue by sandilya-siftly** [eneim/kohii#170]
@eneim  I have an activity, which has a ViewPager which in turn holds the PlayerView. When the app goes to the background (on clicking the home button), I want the playback to be stopped. 

Apologies, I couldn't find any documentation for the same. Could you please let me understand how to do the same?

**Comment by sandilya28** [comment]
In short, I want to control the start and stop of the player.

**Comment by sandilya-siftly** [comment]
Thank you :D, found out we need to use `Manager.OnSelectionListener` to get the current playback and then `Manager` from the `kohii.register`.

**Comment by ghost** [comment]
may you please explain the usage clearly I don't see any setOnSelectionListener in the Manager
