### ISSUE TITLE
Kohii with fragment replace

### ISSUE THREAD

**Issue by yasinalm** [eneim/kohii#180]
**Intro:** Thank you for sharing this amazing repository. I am working on a simple application based on the Fbook sample. I have a Fbook fragment (let's call FB1) in the MainActivity. When there is a search, I replace the existing Fragment container with a newInstance of the Fbook fragment (let's call FB2) and add it to the back stack. I use the same fragment provided in the sample. I can do these so far.

**Desired behaviour:** When I click the back button on FB2, I want to return to FB1.
**Problem:** When I click the back button (even twice), it does not return to FB1. Instead, FB2 remains on the screen with video playing. On the second back press, it kills the MainActivity with FB2 visible.

**Approach:** I tried playing with the `onBackPressed` function in the MainActivity and the `consumeBackPress` in the fragment. They did not change anything. I think this is related to how Kohii manages the fragments and registers the views but I couldn't figure out the correct configuration.

Any help is much appreciated!

**Comment by eneim** [comment]
@yasinalm Can you obtain the desired behavior _without_ using Kohii?  

I assume the issue is how you use add the FB to the backstack, because Kohii doesn't talk to the FragmentManager or the Back Stack. If you believe it is the issue of Kohii, please let me know which API may cause that.

**Comment by yasinalm** [comment]
I have been working on this issue for a while. Currently, I cannot reproduce the issue. I will update this issue if I can reproduce it with Kohii. Thanks for your help!
