### ISSUE TITLE
Adding new video to adapter continues to play the previous top cached video.

### ISSUE THREAD

**Issue by muigukenneth** [eneim/kohii#20]
First of all thank you for this awesome library. I am facing an issue when i add  a new video to the adapter the previous top video is the one which continues to play. 

How can i refresh the cache tags. e.g like update the tag 0 with the a null cache since its a new video and update the previous cache 0 to cache 1 and so on ? When i refresh the items on the adapter.

**Comment by eneim** [comment]
@muigukenneth How is your VideHolder and Adapter? It seems that you are using same tags for different position. A video tag must be unique.

**Comment by muigukenneth** [comment]
@eneim Am setting the tag as the item position so it is always unique. Here is my Adapter:

`class VideosAdapter(
    private val context: Context, val fragment: VideosFragment, val kohii: Kohii,
    val manager: PlaybackManager
) :
    PagedListAdapter<Post, VideosAdapter.VideosViewHolder>(PostDiffCallback()), View.OnClickListener,
    View.OnLongClickListener, FastScroller.SectionIndexer {

    private var mCallback: VideosAdapterListener? = null
    var reBinder: Rebinder? = Rebinder("0", PlayerView::class.java)

    init {
        this.mCallback = fragment
    }


    override fun onCreateViewHolder(
        parent: ViewGroup,
        viewType: Int
    ): VideosViewHolder {
        val view = LayoutInflater.from(parent.context)
            .inflate(R.layout.row_videos, parent, false)
        return VideosViewHolder(view, this, kohii, manager, mCallback) {
            fragment.currentPlayerInfo?.rebinder != it
        }
    }

    override fun onBindViewHolder(holder: VideosViewHolder, position: Int) {
        val dataObject = getItem(position)!!
        holder.itemView.tag = "item:$position"
        holder.textViewName.text = dataObject.userName
        if (dataObject.userImageUrl.isNullOrEmpty()) {
            val generator = ColorGenerator.MATERIAL// or use DEFAULT
            val color1 = generator.getColor(dataObject.uniqueId)
            val drawable = TextDrawable.builder()
                .beginConfig()
                .textColor(Color.WHITE)
                .useFont(Typeface.DEFAULT)
                .bold()
                .toUpperCase()
                .endConfig()
                .buildRound(if (dataObject.userName.isEmpty()) "#" else dataObject.userName.substring(0, 1), color1)
            holder.roundedImageView.setImageDrawable(drawable)
        } else {
            Glide.with(context).load(dataObject.userImageUrl)
                .transition(ImageUtils.requestAvatarTransitionOptions())
                .apply(ImageUtils.requestAvatarOptions(dataObject.profileImageSignature))
                .into(holder.roundedImageView)
        }
        if (dataObject.caption.isEmpty()) {
            ViewUtil.hideView(holder.textViewCaption)
        } else {
            holder.textViewCaption.text = dataObject.caption
            ViewUtil.showView(holder.textViewCaption)
        }
        if (dataObject.likeCount > 0) {
            holder.textViewLaughs.text = String.format(
                "%s %s", dataObject.likeCount.toString(),
                if (dataObject.likeCount == 1) holder.itemView.resources.getString(R.string.laugh)
                else holder.itemView.resources.getString(R.string.laughs)
            )
            ViewUtil.showView(holder.textViewLaughs)
        } else {
            ViewUtil.hideView(holder.textViewLaughs)
        }

        if (dataObject.viewCount > 0) {
            holder.textViewViews.text = String.format(
                "%s %s", dataObject.viewCount.toString(),
                if (dataObject.viewCount == 1) holder.itemView.resources.getString(R.string.view)
                else holder.itemView.resources.getString(R.string.views)
            )
            ViewUtil.showView(holder.textViewViews)
        } else {
            ViewUtil.hideView(holder.textViewViews)
        }
        if (dataObject.commentCount > 0) {
            holder.textViewComments.text = String.format(
                "%s %s", dataObject.commentCount.toString(),
                if (dataObject.commentCount == 1) holder.itemView.resources.getString(R.string.comment)
                else holder.itemView.resources.getString(R.string.comments)
            )
            ViewUtil.showView(holder.textViewComments)
        } else {
            ViewUtil.hideView(holder.textViewComments)
        }
        if (dataObject.shareCount > 0) {
            holder.textViewShares.text = String.format(
                "%s %s", dataObject.shareCount.toString(),
                if (dataObject.shareCount == 1) holder.itemView.resources.getString(R.string.share)
                else holder.itemView.resources.getString(R.string.shares)
            )
            ViewUtil.showView(holder.textViewShares)
        } else {
            ViewUtil.hideView(holder.textViewShares)
        }

        Glide.with(holder.itemView.context)
            .load(Base64.decode(dataObject.thumbNail, Base64.DEFAULT))
            .apply(ImageUtils.requestPagerOptions())
            .into(holder.imageViewThumbnail)
        if (dataObject.isLiked) holder.buttonLaugh.setTextColor(ContextCompat.getColor(context, R.color.colorAccent))
        else holder.buttonLaugh.setTextColor(ContextCompat.getColor(context, R.color.colorSecondaryText))
        val laugh = IconicsDrawable(holder.itemView.context)
            .icon(FontAwesome.Icon.faw_grin_tears)
            .color(
                if (dataObject.isLiked) ContextCompat.getColor(context, R.color.colorAccent).toIconicsColor()
                else ContextCompat.getColor(context, R.color.colorSecondaryText).toIconicsColor()
            )
            .size(30.toIconicsSizeDp())
        holder.buttonLaugh!!.setCompoundDrawablesWithIntrinsicBounds(laugh, null, null, null)
        val comment = IconicsDrawable(holder.itemView.context)
            .icon(FontAwesome.Icon.faw_comment)
            .color(ContextCompat.getColor(context, R.color.colorSecondaryText).toIconicsColor())
            .size(27.toIconicsSizeDp())
        holder.buttonComment!!.setCompoundDrawables(comment, null, null, null)
        val share = IconicsDrawable(holder.itemView.context)
            .icon(GoogleMaterial.Icon.gmd_share)
            .color(ContextCompat.getColor(context, R.color.colorSecondaryText).toIconicsColor())
            .size(24.toIconicsSizeDp())
        holder.buttonShare!!.setCompoundDrawablesWithIntrinsicBounds(share, null, null, null)
        holder.textViewTime.text =
            DateRelativeTimeUtils.getBriefRelativeTimeSpanString(
                context,
                Locale.getDefault(),
                dataObject.createdAt.time
            )
        holder.buttonPlayAgain.setOnClickListener {
            if (!holder.buttonPlayAgain.isVisible) return@setOnClickListener
            // Once completed, a Playback needs to be reset to starting position.
            holder.playback?.rewind()
            reBinder = Rebinder(position.toString(), PlayerView::class.java)
            reBinder?.rebind(kohii, holder.playerView) { playback ->
                playback.addPlaybackEventListener(holder)
                holder.buttonVolume.isSelected = !playback.volumeInfo.mute
                holder.playback = playback
            }
        }
//        holder.itemView.setOnClickListener(this)
        holder.buttonLaugh.setOnClickListener(this)
        holder.buttonComment.setOnClickListener(this)
        holder.buttonShare.setOnClickListener(this)
        holder.materialIconViewOptions.setOnClickListener(this)
        holder.linearLayoutProfile.setOnClickListener(this)
        holder.linearLayoutInteractions.setOnClickListener(this)
//        holder.itemView.setOnLongClickListener(this)
        holder.itemView.tag = "item:$position"
        holder.buttonLaugh.tag = "laugh:$position"
        holder.buttonComment.tag = "comment:$position"
        holder.buttonShare.tag = "share:$position"
        holder.materialIconViewOptions.tag = "options:$position"
        holder.materialIconViewOptions.setTag(R.id.textViewTime, holder.textViewTime)
        holder.linearLayoutProfile.tag = "profile:$position"
        holder.linearLayoutInteractions.tag = "interactions:$position"
        holder.buttonLaugh.setTag(R.id.instaLikeLayout, holder.instaLikeView)
        holder.buttonLaugh.setTag(R.id.dataObject, dataObject)
    }


    class VideosViewHolder(
        override val containerView: View,
        val adapter: VideosAdapter,
        val kohii: Kohii,
        val manager: PlaybackManager,
        val mCallback: VideosAdapterListener?,
        val shouldBind: (Rebinder?) -> Boolean

    ) : BaseViewHolder(containerView), LayoutContainer, PlaybackEventListener {

        var playback: Playback<*>? = null
        private var videoSources: Post? = null

        override fun beforePlay(playback: Playback<*>) {
            KLog.e("Video", "before play")
            containerView.imageViewThumbnail.isVisible = false
            containerView.buttonPlayAgain.isVisible = false
        }

        override fun afterPause(playback: Playback<*>) {
            KLog.e("Video", "after pause")
            containerView.imageViewThumbnail.isVisible = true
        }

        override fun onCompleted(playback: Playback<*>) {
            playback.removePlaybackEventListener(this@VideosViewHolder)
            containerView.imageViewThumbnail.isVisible = true
            containerView.buttonPlayAgain.isVisible = true
            val tag = (itemView.tag as String).split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
            val index = Integer.parseInt(tag[1])
            mCallback!!.onVideoViewComplete(index)
        }

        internal fun dispatchBindVideo(position: Int, reBinder: Rebinder?) {
            videoSources = adapter.getItem(position)
            KLog.e("Video", "bind " + videoSources!!.caption)
            val binder = kohii.setUp(videoSources!!.content)
                .with {
                    tag = position.toString()
                    KLog.e("Video", "tag "+tag)
                }
            if (!shouldBind(reBinder)) {
                // Selected = this ViewHolder should not own the Playback
                // do not bind to PlayerView
                KLog.e("Video", "do not binder")
            } else {
                KLog.e("Video", "binder")
                // bind the Video to PlayerView
                containerView.playerView.invalidate()
               binder.bind(containerView.playerView) { playback ->
                    playback.addPlaybackEventListener(this@VideosViewHolder)
                    containerView.buttonVolume.isSelected = !playback.volumeInfo.mute
                    this@VideosViewHolder.playback = playback
                }
            }

            containerView.buttonPlayAgain.isVisible = playback?.playbackState == Player.STATE_ENDED
        }

    }

    override fun onLongClick(v: View): Boolean {
        // TODO Auto-generated method stub
        val tag = (v.tag as String).split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        val index = Integer.parseInt(tag[1])

        mCallback?.onItemClicked(index, true)
        return true
    }

    override fun onClick(v: View) {
        // TODO Auto-generated method stub
        val tag = (v.tag as String).split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        val index = Integer.parseInt(tag[1])
        when {
            tag[0] == "item" -> mCallback?.onItemClicked(index, false)
            tag[0] == "laugh" -> {
                val dataObject: Post = v.getTag(R.id.dataObject) as Post
                val instaLikeLayout: InstaLikeView = v.getTag(R.id.instaLikeLayout) as InstaLikeView
                if (dataObject.isLiked) {
                    instaLikeLayout.setLikeColor(ContextCompat.getColor(context, R.color.colorAccent))
                    instaLikeLayout.setLikeDrawable(
                        IconicsDrawable(v.context)
                            .icon(FontAwesome.Icon.faw_meh1)
                            .color(Color.WHITE.toIconicsColor())
                            .size(30.toIconicsSizeDp())
                    )
                    instaLikeLayout.start()
                } else {
                    instaLikeLayout.setLikeColor(ContextCompat.getColor(context, R.color.colorAccent))
                    instaLikeLayout.setLikeDrawable(
                        IconicsDrawable(v.context)
                            .icon(FontAwesome.Icon.faw_grin_tears1)
                            .color(Color.WHITE.toIconicsColor())
                            .size(30.toIconicsSizeDp())
                    )
                    instaLikeLayout.start()
                }
                mCallback?.onLaughClicked(index, false, v, !dataObject.isLiked)
            }
            tag[0] == "comment" -> mCallback?.onCommentClicked(index, false, v)
            tag[0] == "share" -> mCallback?.onShareClicked(index, false, v)
            tag[0] == "options" -> {
                val textViewTime: TextView = v.getTag(R.id.textViewTime) as TextView
                mCallback?.onOptionsClicked(index, false, textViewTime)
            }
            tag[0] == "profile" -> mCallback?.onProfileClicked(index, false, v)
            tag[0] == "interactions" -> mCallback?.onInteractionsClicked(index, false, v)
        }
    }
    fun getObject(position: Int): Post {
        return getItem(position)!!
    }
    override fun getSectionText(position: Int): String {
        return if (position < 0 || position >= itemCount) {
            '#'.toString()
        } else {
            if (itemCount > 0) {
                val dataObject = getItem(position)!!
                DateUtils.formatTime(dataObject.createdAt)
            } else {
                '#'.toString()
            }
        }
    }

    override fun onViewAttachedToWindow(holder: VideosViewHolder) {
        super.onViewAttachedToWindow(holder)
        val tag = (holder.itemView.tag as String).split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        val index = Integer.parseInt(tag[1])
        (holder as? VideosViewHolder)?.dispatchBindVideo(index, reBinder)
    }
}`

**Comment by eneim** [comment]
@muigukenneth what do you want to do with this line?

```Kotlin
var reBinder: Rebinder? = Rebinder("0", PlayerView::class.java)
```

the ``tag`` passed to a ``Rebinder`` need to be unique too.

Also, please try to simplify your code to the minimum that can reproduce the issue. At least remove all place for text setting and binding.

**Comment by muigukenneth** [comment]
@eneim  I am re-assigning the reBinder with a unique tag  `reBinder= Rebinder(position.toString(), PlayerView::class.java)` when binding the views. Check updated code above.

**Comment by eneim** [comment]
@muigukenneth Ok. As you are using the position for the ID (which is not suggested. What I do in the demo is simply for demo purpose. If the name itself is not obvious that it must be unique across Activities, I will need to update current comment/doc). 

In practice, I believe there is no such situation where 2 views using the same video. The recommended way is, you handle the tag migration by yourself. The reason is, Kohii has nothing to know or to do with Adapter/RecyclerView. All it does is cache the tag to its resource. If you have the tag uniquely, independent from the adapter position, it will be fine.

--

To demonstrate that, let say, initially in your list, first video (order 0) has the tag of "video_tag_0". Once you add another one on top, the previous video become the second one (order 1), **but** its tag must remain being "video_tag_0". You need to generate a new tag for the newly become the first video.

Imagine that, if you line up in a queue to a coffee shop, regardless of which position you are, your ID card number is unchanged.

How to do this is, however, up to you.

**Comment by muigukenneth** [comment]
@eneim Thank you for the explanation. I now understand how the cache works. I have just replaced the tag with a unique id and its working well. I think you should update the doc and discourage using the adapter position as a unique id since some guys will face the same issue if they delete or insert new data on their adapters.

**Comment by eneim** [comment]
@muigukenneth yeah sure. thanks for using the lib.
