### ISSUE TITLE
ViewPager2 support

### ISSUE THREAD

**Issue by mym0404** [eneim/kohii#32]
I want to use kohii with ViewPager2(because I want use vertical paging).

I cloned viewpager2 of google code and modified RecyclerView access modifier with public and setted host as RecyclerView in ViewPager2.

Then it worked.

I have no idea about side effect about that now...

Do you have any plan to support ViewPager2 with Kohii??

**Comment by eneim** [comment]
@mym0404 Although it is still in development, ViewPager2 is supported now, You can find a 'compact' sample here: [ViewPager2](https://github.com/eneim/kohii/tree/dev-v1/kohii-sample/src/main/java/kohii/v1/sample/ui/pager2)

**Comment by mym0404** [comment]
I think your link only works with usage ViewPager2 as Fragment Pager...

In my case, if I use RecyclerView.Adapter<VH> for ViewPager2 adapter, no register one error invoked.

**Comment by eneim** [comment]
@mym0404 please checkout latest commit in sample app. I add Pager3Fragment for this case. The point is other than registering the ViewPager, you also need to registering the ViewPager's RecyclerView. It looks like a workaround, but it is a reasonable implementation.

**Comment by mym0404** [comment]
ahhh getChildAt(0) is key... thank you
