### ISSUE TITLE
video not play when orientation is Landscape 

### ISSUE THREAD

**Issue by yudikarma** [eneim/kohii#34]
i try your library for playvideo in recyclerview. but the problem is when orientation change to landscape the video is not auto play, maybe this cause my VideoViewholder height is so big. see this [pictures](https://imgur.com/WzdSE2z)

and i want to ask, how to pause and resume the video manual ? cause i need to pause and play in some event. thanks for this awesome library

**Comment by eneim** [comment]
@yudikarma Yeah it seems to be the size of Video is too big. If you let your Activity recreate on config change, please try to use different Video area size to **verify** the behavior first.

Kohii allows you to manually control the Video. It is just not working as I expected so I didn't push a sample for it. Please wait for next update (maybe release A12 or A13).

**Comment by yudikarma** [comment]
can i use this library for my production app ? or you not yet recommendet cause not yet stable realise ?

**Comment by eneim** [comment]
If only the auto playback in RecyclerView or ViewPager, it can be useful. But from my experience, the requirement will not stop there. So it is not recommended to use Kohii in production yet.

**Comment by yudikarma** [comment]
i just wanna only use for auto playback in RecyclerView, how ? recommended  to my production ?

**Comment by eneim** [comment]
@yudikarma If your use case is just this It is fine. But be aware about my warning when you need more complicated features.

**Comment by yudikarma** [comment]
oke fine.. so i have two fragment with tabslayout and viewpager, how to make my recyclerview with video to pause when user go to or swipe to other fragmet in tab layout ? i not yet find this case in your sample.. btw this library realy help my task. you save my time for 3 day stuck. thanks for your work

**Comment by yudikarma** [comment]
i failed to build you sample project in this library, please change crashlystic from fabric to firebase analystic

**Comment by eneim** [comment]
@yudikarma Ohh forget it in last commit (chaging fabric to full firebase is in plan ...). You can change the build.gradle (to remove stuff that requires fabric) and rebuild.

**Comment by eneim** [comment]
> oke fine.. so i have two fragment with tabslayout and viewpager, how to make my recyclerview with video to pause when user go to or swipe to other fragmet in tab layout ? i not yet find this case in your sample.. btw this library realy help my task. you save my time for 3 day stuck. thanks for your work

Do you mean your RecyclerView is inside a Fragment which is a page of the ViewPager? You can implement it just like normal RecyclerView demo but also register the ViewPager to Kohii.

```kotlin
// Setup in MainFragment that owns the ViewPager
Kohii[this].register(this@MainFragment, viewPager)

// Setup in PageFragment which is page of ViewPager
Kohii[this].register(this@PageFragment, recyclerView)
```

**Comment by yudikarma** [comment]
work like a charm :) big thanks @eneim

**Comment by yudikarma** [comment]
@eneim i wanna ask 1 more.. 
whats function of taget host ? i wanna implement toogle volume btn, but after try to following by example form Kohie Recycler view 4. but after that, my video in recyclerview always playback from start when notifyitemchange called

**Comment by yudikarma** [comment]
thanks @eneim  iam already fix for video pause on notifyitemchange called, mistake to update viewholder use notifyitemchange, i fix bye use your logik to handle volume click, big thanks
