### ISSUE TITLE
Android Studio Cannot find Kohi after update news Kohi version

### ISSUE THREAD

**Issue by yudikarma** [eneim/kohii#37]
after update kohii in my build gradle module. android studio cannot find any Kohii library..
this is my implementation build gradle
`implementation "im.ene.kohii:kohii:1.0.0.2010004-A11"`
`implementation "com.google.android.exoplayer:exoplayer:2.10.4"`

**Comment by eneim** [comment]
@yudikarma Do you have ``maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }`` in your ``repositories`` block in build.gradle ?

**Comment by yudikarma** [comment]
no, please added to readme thanks @eneim

**Comment by eneim** [comment]
@yudikarma Ok I will update the README in next push. It is time I think.

**Comment by yudikarma** [comment]
iam keep in same proble. may be i have another misstake[capture error](https://imgur.com/a/aIYTBvs)

**Comment by eneim** [comment]
<img width="659" alt="Screen Shot 2019-10-15 at 13 59 14" src="https://user-images.githubusercontent.com/1776230/66801429-0152b680-ef54-11e9-90f5-6534911583ca.png">

@yudikarma This is the block you should add the snapshot maven repo (notice the "allprojects" block).

**Comment by yudikarma** [comment]
add Implementation for Kohii news vrsion
![image](https://user-images.githubusercontent.com/20062470/66804732-779fea80-ef4d-11e9-84b8-9e05b039750c.png)

add the snapshot maven repo in Build.gradle project
![image](https://user-images.githubusercontent.com/20062470/66804765-8c7c7e00-ef4d-11e9-9f5f-693eb2eb8f0d.png)

after sync.. i got this error when build the app
![image](https://user-images.githubusercontent.com/20062470/66804797-a3bb6b80-ef4d-11e9-8177-d6da6ae41394.png)

**Comment by eneim** [comment]
@yudikarma @Diegofr104 I think there was a missing config that stripped out many things in the release artifact. Let me figure out a fix real quick. FYI the maven works, but what it downloads doesn't work.

<img width="503" alt="Screen Shot 2019-10-17 at 9 52 31" src="https://user-images.githubusercontent.com/1776230/66969287-fa4ab600-f0c3-11e9-9616-8ac6be374e81.png">
