### ISSUE TITLE
audio and video resume play in background

### ISSUE THREAD

**Issue by yudikarma** [eneim/kohii#38]
open kohii + recyclerview -> when video play then click home button, and video will pause. then lock your screen (without open other app), -> un-loack your sceen -> the video will auto resume (with audio)..

this happen in your sample app with redmi Note 7 (android P). how to disable or make audio or video not running in background ??

**Comment by eneim** [comment]
Thanks for the issue. Let me investigate this and the notifyitemchange.

**Comment by eneim** [comment]
<img width="1065" alt="Screen Shot 2019-10-15 at 13 33 57" src="https://user-images.githubusercontent.com/1776230/66800544-82a84a00-ef50-11e9-87f7-386aa2c96630.png">

@yudikarma Please refer to the screenshot above. If you are willing to use Kohii from source code, you can make change like this. Though I'm investigating other side-effect and screen on/off event by system to ensure the overall behavior, an official push will have to wait for a few days.
