### ISSUE TITLE
Project not build with new version

### ISSUE THREAD

**Issue by DrPechkin** [eneim/kohii#46]
`
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find kohii.v1:kohii-core:unspecified.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/kohii/v1/kohii-core/unspecified/kohii-core-unspecified.pom
       - https://dl.google.com/dl/android/maven2/kohii/v1/kohii-core/unspecified/kohii-core-unspecified.jar
       - https://jcenter.bintray.com/kohii/v1/kohii-core/unspecified/kohii-core-unspecified.pom
       - https://jcenter.bintray.com/kohii/v1/kohii-core/unspecified/kohii-core-unspecified.jar
     Required by:
         project :app > im.ene.kohii:kohii-exoplayer:1.0.0.2010004-B1
`

**Comment by eneim** [comment]
@DrPechkin Sorry just realize I did a bad setting in release script. Fixing it now.

**Comment by eneim** [comment]
@DrPechkin B2 would fix this issue. I will remove B1 from jcenter to prevent this.

**Comment by DrPechkin** [comment]
@eneim Thanks!

**Comment by DrPechkin** [comment]
@eneim  After adding the library my buttons lost their color shades

**Comment by eneim** [comment]
@DrPechkin what buttons? How are they defined in your xml? I do not have any touch to UIs other than PlayerView. Can you show your dependencies to Material Design library?

**Comment by DrPechkin** [comment]
@eneim I think this is a bug because of what you are using "com.google.android.material:material:1.1.0-beta02"

**Comment by eneim** [comment]
@DrPechkin Hmm I don't know why it forces your app to use my dependency, but please try this https://developer.android.com/studio/build/dependencies#exclude_dependencies to see if it help. I will double check later.
