### ISSUE TITLE
Using kohii in 2 activities

### ISSUE THREAD

**Issue by Diegofr104** [eneim/kohii#53]
Im having an issue about using kohi in 2 activities.

The problem is when i first open the activity 1 works fine, then open the activity 2 and works fine too but.. when i try to open again activity 1 it crash with this message 

 java.lang.IllegalArgumentException: Failed requirement.
        at kohii.v1.core.Binder.providePlayable(Binder.kt:72)
        at kohii.v1.core.Binder.bind(Binder.kt:52)

What it means about "Failed requirement".

**Comment by talha01sayed** [comment]
I am getting the same error. any update on this?
