### ISSUE TITLE
Can't register in activity

### ISSUE THREAD

**Issue by silvershort** [eneim/kohii#54]
Using the Java language,
Java8 use specified in gradle.

```Java
public class DetailActivity extends AppCompatActivity {

    private ViewPager2 viewpager2;
    private Kohii kohii;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.detail_activity);

        detail_viewpager2 = findViewById(R.id.detail_viewpager2);

        kohii = Kohii.get(this);
        kohii.register(this).addBucket(detail_viewpager2);
    }
}
```

kohii.register( >>> this <<<)

I get an error here

**Comment by eneim** [comment]
@silvershort What is the error message?

**Comment by silvershort** [comment]
> @silvershort What is the error message?

Cannot resolve method 'register($PACKAGENAME.DetailActivity)'

**Comment by silvershort** [comment]
The parameter type shows fragment and fragmentActivity but not Activity

**Comment by eneim** [comment]
@silvershort looks weird. Can you try this `kohii.register(this@DetailActivity)`?

DetailActivity extends AppCompatActivity so it should be Ok.

**Comment by eneim** [comment]
@silvershort Looks weird. Can you paste the full logcat here?

**Comment by silvershort** [comment]
> @silvershort Looks weird. Can you paste the full logcat here?

error: no suitable method found for register(MainActivity)
method Engine.register(Fragment,MemoryMode) is not applicable
(actual and formal argument lists differ in length)
method Engine.register(FragmentActivity,MemoryMode) is not applicable
(actual and formal argument lists differ in length)

=====================================

https://imgdb.in/grZ6

If you look at the photo in the link above, you can see only fragment and FragmentActivity types, not activity types.

**Comment by silvershort** [comment]
https://github.com/silvershort/KohiiTest

I posted some test code on my github that gives an error. confirm onegaishimasu

**Comment by eneim** [comment]
@silvershort got the issue. It is because I do not add `JvmOverloads` annotation to the method.

For now you can use it like below:

```java
kohii.register(this, MemoryMode.AUTO).addBucket(detail_viewpager2);
```

**Comment by silvershort** [comment]
> @silvershort 에 문제가 있습니다. `JvmOverloads`메서드 에 주석을 추가하지 않기 때문 입니다.
> 
> 지금은 아래와 같이 사용할 수 있습니다 :
> 
> ```java
> kohii . (등록 이 , MemoryMode . AUTO을 ) . addBucket (detail_viewpager2);
> ```
