### ISSUE TITLE
there are some issues i found when using kohii with recycler view. 

### ISSUE THREAD

**Issue by plutonem-mobile** [eneim/kohii#56]
Hi, eneim. 

I found some issues when i am using kohii with recycler view, here is the scenario.

in my recycler view, i need to update the data every 5 minutes in case there are some more datas come from remote server and each time the recycler get new datas, it triggers 'notifyDataSetChanged' function, then the adapter's 'onBindViewHolder' is triggered.  in the 'onBindViewHolder', i used 'kohii.setup().bind()' function to bind the video to my playerView. so that means, every time the recycler view is updated, the kohii will call the bind() function.

so here is the problem, in the kohii.bind() function, there is a providePlayable() function and in this function, it need the playable of same tag must have the same Media data - 'require(cache.media == media)', but every time my recycler view is being updated, the media url data is different because i have to play different video. so my application gets to crash.

can you help me with this issue?

**Comment by plutonem-mobile** [comment]
![issue](https://user-images.githubusercontent.com/8728579/74088730-6c606400-4ad4-11ea-9de2-ec2a288e8fd0.png)

this 'renderOrder' function is called by adapter's 'onBindViewHolder' and here is how i trigger kohii

**Comment by plutonem-mobile** [comment]
![issue2](https://user-images.githubusercontent.com/8728579/74088773-db3dbd00-4ad4-11ea-8c7e-a04cbd7333f8.png)

and bug happens here.

**Comment by plutonem-mobile** [comment]
when the recycler view getting new order from remote server, it triggers 'notifyDataSetChanged' function, and the order with tag No.1 becomes No.2, and the new order with different media url becomes tag No.1. I guess that is why it crashes

**Comment by plutonem-mobile** [comment]
![issue3](https://user-images.githubusercontent.com/8728579/74088904-420fa600-4ad6-11ea-876e-40b6a1891044.png)

this is how i set the videoTag

**Comment by plutonem-mobile** [comment]
is it okay if I change the way the make the Tag? because in this mode, every time the recycler view is updated, the tag No.1 will point to the new order with different media data(because the original order's adapter position has changed to 2), so it will crash.

if i change the way to make the tag for example, generate a random number, so every time the adapter's onBindViewHolder function is being triggered, it will generate a new tag. is it fixing the problem?

**Comment by plutonem-mobile** [comment]
okay, eneim. i handle it successfully!

the issue is because what i said upward, the way to create videoTag. the previous method can lead to the old tag point to the new data in recycler view.

i change my method to this 

![issue1](https://user-images.githubusercontent.com/8728579/74090506-029d8580-4ae7-11ea-9bcc-fc9184381a8b.png)

and now if my recycler view get updated, the new order from remote server will get correct tag for itself and will not have any conflict with the old orders.

**Comment by plutonem-mobile** [comment]
Hi, eneim, can you help me with this proble?

it is a big issue and i don't know how to fix this yet

**Comment by eneim** [comment]
Hey, first you should use other method than notifyDataserChange. This method is the least performant trigger of RecyclerView and will cause everything to be re-bound.

Second, yes you need unique tag for your video. Using adapterPosition is for demo only. Please make it unique by your own mechanism.
