### ISSUE TITLE
Muted videos are stealing audio focus from other apps

### ISSUE THREAD

**Issue by spencergriffin** [eneim/kohii#57]
If I am playing audio in another app, and start a video with kohii, the audio focus is lost from the other app.

I am calling `kohii.applyVolumeInfo(VolumeInfo(mute = true), manager, Scope.GLOBAL)` to mute the videos.

Do you know how I can avoid requesting audio focus so the audio will continue in the background app?

**Comment by eneim** [comment]
Do you mean your app that use Kohii loses audio focus? Or do you mean that other app loses audio focus to your app that uses Kohii?

By default when setting audio to mute Kohii will give up audio focus. This way your video will not pause other app’s video. It can be customized but not as straight forward in lastest release. Hint: please check the source code of KohiiPlayer. You can create your own PlayerProvider with custom setVolumeInfo logic.

**Comment by spencergriffin** [comment]
The latter, the other app loses audio focus to my app. Creating my own PlayerProvider does solve the problem; however, I may be missing something but it also requires creating a lot of other classes because I can't find a way to inject it.

**Comment by eneim** [comment]
@spencergriffin At 1.0.0 I will open the constructor/builder for Kohii to help you inject just the code you need. For now I want to confirm the abstraction layer first. Please wait.
