### ISSUE TITLE
when I open the downloaded source from Android Studio 3.5.3, I meet an error

### ISSUE THREAD

**Issue by wann2** [eneim/kohii#58]
I has been looking for the solution in viewpager2 + video player, but the Kohii seems to be awesome for me.
I'd like to use Kohii, but when I open the downloaded source from Android Studio 3.5.3, I meet the follow error. Could you help me how to fix it?

ERROR: Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.3.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.3.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository

<img width="1744" alt="스크린샷 2020-02-16 15 02 20" src="https://user-images.githubusercontent.com/8732515/74599975-beede180-50cd-11ea-8f34-1a13b925f611.png">

**Comment by eneim** [comment]
Please use AS 3.6.0 latest RC to develop Kohii ...
