### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by mariuspena** [eneim/kohii#59]
hey @eneim ! 
I was trying to test out your solution in a recycler view (just like instagram plays/pauses videos) 

on this line 
`        Kohii kohii = new Kohii(this.getContext());
`
I get this:
`Kohii(android.context.Contex) has private access in kohii.v1.exoplayer.Kohii`

here is my grade build dependencies:

// ExoPlayer
    def exo_player_version = '2.11.2'
    implementation "com.google.android.exoplayer:exoplayer-core:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-ui:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-dash:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-hls:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:$exo_player_version"

    // ExoPlayer extension for instagram like playable videos in recyclerView
    implementation "im.ene.kohii:kohii-core:1.0.0.2010004-B2" // core library
    implementation "im.ene.kohii:kohii-exoplayer:1.0.0.2010004-B2" // default support for ExoPlayer
   // implementation "com.google.android.exoplayer:exoplayer:2.10.4" // required ExoPlayer implementation.

but I get this error:

`AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/na/.gradle/caches/transforms-2/files-2.1/fe80929c59f3fa8dceee63b3420012ea/kohii-exoplayer-1.0.0.2010004-B2/res/layout/kohii_player_spherical_view.xml","position":{"startLine":17}}],"original":"/Users/na/.gradle/caches/transforms-2/files-2.1/fe80929c59f3fa8dceee63b3420012ea/kohii-exoplayer-1.0.0.2010004-B2/res/layout/kohii_player_spherical_view.xml:18: AAPT: error: 'spherical_view' is incompatible with attribute surface_type (attr) enum [none=0, spherical_gl_surface_view=3, surface_view=1, texture_view=2, video_decoder_gl_surface_view=4].\n    ","tool":"AAPT"}
`

**Comment by loicsiret** [comment]
As mentioned in the readme, in java you have to use static initialization, not calling Kohii constructor :

```
// Java
// 1. Initialization in Fragment or Activity
Kohii kohii = Kohii.get(this);
```

**Comment by mariuspena** [comment]
oh my bad!!

one more question: when binding in adapter's viewholders what should I use ?
kohii.setUp(url, <what is this second parameter about?>).bind(playerView);

**Comment by mariuspena** [comment]
I try to setup kohii in the adapter, but the setUp method needs another parameter besides url.
I searched the samples, read the readme, but I cannot figure it out.
@eneim can you help ?
thanks a lot

**Comment by eneim** [comment]
Maybe this version is not updated with @JvmOverloads to support Java. I will check it when I get my hand on the code.

**Comment by mariuspena** [comment]
@eneim I would be eternally grateful :)

**Comment by eneim** [comment]
@mariuspena please try latest release: 1.0.0.2010004-beta5

**Comment by mariuspena** [comment]
hey @eneim 

my build gradle is 

// ExoPlayer
    def exo_player_version = '2.11.2'
    implementation "com.google.android.exoplayer:exoplayer-core:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-ui:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-dash:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-hls:$exo_player_version"
    implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:$exo_player_version"


    // Kohii for exoplayer in recyclerview
    def kohii_version = '1.0.0.2010004-beta.5'
    implementation "im.ene.kohii:kohii-core:$kohii_version" // core library
    implementation "im.ene.kohii:kohii-exoplayer:$kohii_version" // default

In my ViewHolder:
private final PlayerView playerView; // from explayer library

onBind:
String videoUrl = "https://www.radiantmediaplayer.com/media/bbb-360p.mp4";
kohii.setUp(videoUrl).bind(playerView);

but I get this:
bind (ViewGroup, Function1<? super Playback, Unit>)in Binder cannot be applied to (PlayerView)

**Comment by eneim** [comment]
@mariuspena Can you try with ExoPlayer 2.10.4? I believe it would not be different, but just to make sure.

In my environment, it looks fine though. The code below doesn't alert me anything:

```Java
    PlayerView playerView = new PlayerView(this);
    Kohii kohii = Kohii.get(this);
    kohii.register(this).addBucket(getWindow().getDecorView());

    kohii.setUp("dummy url").bind(playerView, playback -> {
      // TODO
      return null;
    });
```

**Comment by mariuspena** [comment]
@eneim it works! :) thanks a bunch! I will be back with more questions

**Comment by eneim** [comment]
@mariuspena Sounds great. Thanks and your questions are welcome. I will close this issue for now.

**Comment by mariuspena** [comment]
@eneim how can add a listener for onLoadingChanged, onPlayerStateChanged, etc with kohii ?

when I was using it with SimpleExoPlayer I was doing something like this:
`        private void initVideoPlayer() {
            player = new SimpleExoPlayer.Builder(context).build();
            player.setPlayWhenReady(true);
            player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);
            player.setRepeatMode(Player.REPEAT_MODE_ALL);
            player.addListener(new Player.EventListener() {
                @Override
                public void onLoadingChanged(boolean isLoading) {
                    int i=0;
                }
                @Override
                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                    int i=0;
                }
                @Override
                public void onIsPlayingChanged(boolean isPlaying) {
                    int i=0;
                }
            });
            playerView.setPlayer(player);
            playerView.setUseController(false);
        }`

**Comment by mariuspena** [comment]
basically I am looking for the manual controller documentation here: https://github.com/eneim/kohii/blob/dev-v1/docs/usage/advance.md :)

**Comment by eneim** [comment]
@mariuspena Let me answer your question one by one.

About the listener, currently I allow a custom callback: [StateListener](/blob/dev-v1/kohii-core/src/main/java/kohii/v1/core/Playback.kt#L428) which convert the important events from the `EventListener`. The reason I use this one is to avoid the interface changes by ExoPlayer version change. But I can open this in near future. If you are Ok with the StateListener above, you can use it like below:

```java
kohii.setUp(videoUrl, options -> null)
    .bind(new FrameLayout(this), playback -> {
        playback.addStateListener(listener);
        return null;
    });
```

About the manual mute/unmute control, I have a demo that support that: [Echo demo](https://github.com/eneim/kohii/tree/dev-v1/kohii-sample/src/main/java/kohii/v1/sample/ui/echo). The code is in Kotlin though. You can download the APK in release page to try it out.

About the manual play/pause control, it is something under design. I had a few iterations, but none works as well as I expect. Leave some comment here: [Master.kt](https://github.com/eneim/kohii/blob/dev-v1/kohii-core/src/main/java/kohii/v1/core/Master.kt#L59). If you can describe more about your scenario, as detail as possible, I can take that into account to improve the design :D.

Also, for new request/issue report, please create new issue. It helps me to organize the thing and resolve them better and faster :D.
