### ISSUE TITLE
Sync project with gradle gets "For input string: " Error

### ISSUE THREAD

**Issue by plutonem-mobile** [eneim/kohii#65]
Hi, eneim.

I just download the newest release version which you publish 20 days ago. i tried to open it in Android studio but got sync error imediately and cannot open. 

the error look like this. i did not change any file of your release. 

![69d5cd084812ee8fb0113657f38e846](https://user-images.githubusercontent.com/8728579/76572070-ff395780-64f3-11ea-90d3-291d25e5769d.png)

![c58d8e39ccadc26aa1bef0809344922](https://user-images.githubusercontent.com/8728579/76572096-1415eb00-64f4-11ea-8227-5b7f87467514.png)

**Comment by eneim** [comment]
I think it is because your download is not a git repo so a git command fails. Can you try clone the repo instead? Just to make sure.

**Comment by plutonem-mobile** [comment]
yes. i download it directly through zip file, because the speed through git clone is too slow and usually fail eventually. 

is there a way to fix the upfront question if i cannot clone?

**Comment by eneim** [comment]
@plutonem-mobile You will need git to do so:

Run the following commands from the project folder:

```shell
git init
git commit --allow-empty -m "Init"
```

Then open the project by Android Studio. If you are using AS 3.6.1, it will ask you to update the version. Please go to buildSrc/java/kohii, open Dependencies.kt and change:

```
const val androidGradlePlugin = "com.android.tools.build:gradle:3.6.0-rc03"
```

to 
```
const val androidGradlePlugin = "com.android.tools.build:gradle:3.6.1"
```

**Comment by plutonem-mobile** [comment]
ok thanks. i will give it a try.

**Comment by plutonem-mobile** [comment]
so cool, i got it down !
thanks your help again eneim.
