### ISSUE TITLE
Overlapping videos when resize_mode="zoom"

### ISSUE THREAD

**Issue by xibaca** [eneim/kohii#90]
I don't know if this is an issue with Kohii per-se (or with the ExoPlayer backend itself).

When we change the resize mode of PlayerView's such that they zoom in to fill the whole container size, potentially cropping if needed to maintain the video's aspect ratio (this is achieved using `resize_mode="zoom"`), if we have multiple video containers and these containers are close enough, their video feeds overlap, as can be seen in the screenshot below.

![Screenshot from 2020-07-13 11-00-14](https://user-images.githubusercontent.com/465808/87285771-36e2fb00-c4f8-11ea-8a24-c70a346ce674.png)

By the way, thanks so much, amazing library!!

(And feel free to close this issue should the problem be with the underlying ExoPlayer - I just thought this should be worth some investigation at the Kohii level).

**Comment by eneim** [comment]
Interesting. Yeah it seems to be an issue of ExoPlayer, but let me take a look.

**Comment by eneim** [comment]
@guilhermesgb It seems to be an issue if you use SurfaceView as the surface type for the PlayerView. For a quick dirty fix you can try to use TextureView instead. It is not a good workaround but if you need to fix it urgently. I will see if we can have a better fix and will discuss it in ExoPlayer repo when I have a better idea.

**Comment by xibaca** [comment]
Thanks a lot for your time investigating it @eneim :)

It seems that in my case I might be able to get by with a little stretching of these video feeds, but should we need to maintain their aspect ratio, I might resort to this workaround for the meantime.

Thanks and I will try to keep a look on issues over there to learn more about what's going on under the hood :)

**Comment by eneim** [comment]
Just see the same issue is reported to ExoPlayer: https://github.com/google/ExoPlayer/issues/6955 . It's likely that we rely on the Android platform to fix/change the behavior.

**Comment by xibaca** [comment]
Thanks for your time looking at this. Indeed it is rare to be the first to spot a new issue :)

I've too have been using the TextureView fallback as a workaround, as per your suggestion, with no drawbacks.

PS: feel free to close this issue, in case you feel like it doesn't need to be open here.
