### ISSUE TITLE
How to pass authorization header in the library?

### ISSUE THREAD

**Issue by easedroid** [eneim/kohii#97]
@eneim 
Usually we used below in exoplayer,

```kotlin
  val videoSource: MediaSource = ProgressiveMediaSource.Factory(
      DataSource.Factory {
        val dataSource: HttpDataSource = DefaultHttpDataSource("com.example")
        // Set a custom authentication request header.
        dataSource.setRequestProperty("Authorization", bearerToken)
        dataSource
      }
  ).createMediaSource(Uri.parse(streamUri))
```

Now my question is how to add authorization while initiating. I got this one which is used to prepare sources
 
`kohii.setUp(streamUri)`

**Comment by eneim** [comment]
@easedroid You can build Kohii instance using Builder. The code is a bit verbose. Please find the suggestion below:

- Below is the lambda to create a Kohii instance with custom DataSource.Factory:

```kotlin
val kohiiCreator: (Context) -> Kohii = { context ->
    val mediaSourceFactoryProvider = DefaultMediaSourceFactoryProvider(
        // Your custom DataSource.Factory goes here.
        dataSourceFactory = DataSource.Factory {
          val dataSource: HttpDataSource = DefaultHttpDataSource("com.example")
          // Set a custom authentication request header.
          dataSource.setRequestProperty("Authorization", bearerToken)
          dataSource
        },
        // This is mandatory, but you can use DUMMY if you do not need one.
        drmSessionManagerProvider = object : DrmSessionManagerProvider {
          override fun provideDrmSessionManager(media: Media): DrmSessionManager<ExoMediaCrypto>? {
            return DrmSessionManager.DUMMY
          }
        }
    )

    Kohii.Builder(context)
        .setPlayableCreator(
            PlayerViewPlayableCreator.Builder(context)
                .setBridgeCreatorFactory {
                  PlayerViewBridgeCreator(
                      ExoPlayerPool(context = context),
                      mediaSourceFactoryProvider = mediaSourceFactoryProvider
                  )
                }.build()
        )
        .build()
  }
```

My recommendation is to use Kohii as Application-scoped singleton, so you can put the code above to a _Capsule_ (this is an util class in the library):

```kotlin
object KohiiProvider {
    private val capsule = Capsule<Kohii, Context>(creator = kohiiCreator)

    operator fun get(context: Context): Kohii = capsule.get(context)
}

// Get an instance of Kohii using the KohiiProvider object
val kohii = KohiiProvider.get(context) // or KohiiProvider[context]
```

Please try this and let me know. I have plan to simplify the creation of Kohii, but it is not yet available.

**Comment by easedroid** [comment]
@eneim 
I did as you suggested but no luck, It stuck at black screen but I can see the log that it started buffer. Can you please add it to your sample project which can be much easier. The library can be awesome with little changes. It is simpler for normal videos(without auth url's) but with auth streaming is much more difficult.
For my case player view container is taken under a frame layout.

**Comment by eneim** [comment]
@easedroid Please try the code below to inject your custom MediaSourceFactory when you create a Kohii instance.

```Kotlin
object KohiiProvider {

  private val capsule: Capsule<Kohii, Pair<Context, MediaSourceFactory>> =
    Capsule(creator = { (context, factory) ->
      createKohii(context, mediaSourceFactoryCreator = { factory })
    })

  private fun get(context: Context, factory: MediaSourceFactory) = capsule.get(context to factory)

  operator fun get(context: Context) = get(context, /* Your custom MediaSourceFactory */ ProgressiveMediaSource.Factory {
    val dataSource: HttpDataSource = DefaultHttpDataSource("com.example")
    // Set a custom authentication request header.
    dataSource.setRequestProperty("Authorization", "test auth header")
    dataSource
  })
}

// Later
val kohii = KohiiProvider[context]
```

I tried this and the connection contains the necessary headers.

I do not have a server to be able to build a proper example with custom header, but I can add the code to the kohii-sample code later.

**Comment by easedroid** [comment]
@eneim 
Thanks for your help but it's not worked. Here is what I am using in my viewholder

                        ` kohii?.let { kohii ->
                                    kohii.setUp(streamUri) {
                                    tag = "${streamUri}+${position}"
                                    preload = true
                                    repeatMode = Common.REPEAT_MODE_ONE
                                    controller = object : Playback.Controller {
                                        override fun kohiiCanStart(): Boolean = true
                                        override fun kohiiCanPause(): Boolean = true
                                        override fun setupRenderer(
                                            playback: Playback,
                                            renderer: Any?
                                        ) {
                                            binding.playerView.setOnClickListener {
                                                val playable =
                                                    playback.playable ?: return@setOnClickListener
                                                if (playable.isPlaying()) {
                                                    playback.manager.pause(playable)
                                                } else {
                                                    playback.manager.play(playable)
                                                }
                                            }
                                        }

                                        override fun teardownRenderer(
                                            playback: Playback,
                                            renderer: Any?
                                        ) {
                                            binding.playerView.setOnClickListener(null)
                                        }
                                    }
                                    }.bind(binding.playerView)
                                }`
Is it right? or I am doing it in a wrong way?

**Comment by eneim** [comment]
This is when you use Kohii to setup the Video and it has nothing to do with the DataSource. 

Please let me know How do you create the Kohii instance and How did you know that the header doesn't work?

**Comment by easedroid** [comment]
> This is when you use Kohii to setup the Video and it has nothing to do with the DataSource.
> 
> Please let me know How do you create the Kohii instance and How did you know that the header doesn't work?

Thanks @eneim it is working now, it was a silly mistake by me after adding your suggestion I forgot to set visibilty of the layout.
Now I recheck with previous solution which is still not working but who cares the last one more simpler.
Great works man 🥇 , you help me a lot.

You can add this into your sample also, in case anyone require this in future can get it from there without raising issue like me 👍

**Comment by eneim** [comment]
@easedroid Great it helps.
