### ISSUE TITLE
How to get Playable for a ViewGroup?

### ISSUE THREAD

**Issue by saurabhthorat** [eneim/kohii#98]
I've been using [`Manager#findPlayableForContainer()`](https://github.com/eneim/kohii/blob/69f8cc31dfcdf4a1070137fcf898f2b8c6daf891/kohii-core/src/main/java/kohii/v1/core/Manager.kt#L195), but that method has been [removed](https://github.com/eneim/kohii/commit/a38d93a392cb5463c9ae6e81351e575a1c157c94#diff-07814a83daf4bd93a9be192f3917ba77L195) in v1.1.1.2011003. Is there any method that replaces this one, where you can get `Playable` for a `ViewGroup`?

**Comment by eneim** [comment]
@saurabhthorat One you get the Playback instance you can access the Playback's Playable. It is the same thing: https://github.com/eneim/kohii/blob/1d8e8b51f8905aee5d9ee82df022f98e666d00a5/kohii-core/src/main/java/kohii/v1/core/Playback.kt#L371

**Comment by Nishit79** [comment]
@eneim how can we get playback instance can you please write some snippet of code

**Comment by eneim** [comment]
@Nishit79  In the call to `bind` you can pass a callback which gives you the Playback instance once it is bound:

```kotlin
kohii.setUp(videoUrl).bind(container) { playback ->
  // TODO use the Playback here
}
```

An example can be found here: https://github.com/eneim/kohii/blob/91992a5615446660a69e615ef0b63a551c4c55e4/kohii-sample/src/main/java/kohii/v1/sample/ui/fbook/vh/VideoViewHolder.kt#L91

**Comment by Nishit79** [comment]
hi @eneim thanks for the above reply 
one more query I was having how can we use custom controller for exoplayer in Java?

**Comment by eneim** [comment]
@Nishit79 Please find a snippet below:

```Java
    // This setup will use a ControlDispatcher to allow users to control the PlayerView.
    Kohii kohii = Kohii.get(this);

    final Function2<Playback, Object, Unit> setupRendererController = (playback, renderer) -> {
      if (renderer instanceof PlayerView) {
        ControlDispatcher dispatcher = kohii.createControlDispatcher(playback);
        // Kinda dirty cast, please improve it yourself.
        ((PlayerView) renderer).setControlDispatcher(dispatcher);
        ((PlayerView) renderer).setUseController(true);
        ((PlayerView) renderer).setTag(dispatcher);
      }
      return null;
    };

    final Function2<Playback, Object, Unit> teardownRendererController = (playback, renderer) -> {
      if (renderer instanceof PlayerView) {
        ((PlayerView) renderer).setUseController(false);
        Object tag = ((PlayerView) renderer).getTag();
        if (tag instanceof ControlDispatcher) {
          ((PlayerView) renderer).setTag(null);
        }
      }
      return null;
    };

    kohii.setUp(videoUrl, options -> {
          options.setController(new Playback.Controller() {
            @Override public boolean kohiiCanPause() {
              return true;
            }

            @Override public boolean kohiiCanStart() {
              return true;
            }

            @Override
            public void setupRenderer(@NotNull Playback playback, @Nullable Object renderer) {
              setupRendererController.invoke(playback, renderer);
            }

            @Override
            public void teardownRenderer(@NotNull Playback playback, @Nullable Object renderer) {
              teardownRendererController.invoke(playback, renderer);
            }
          });
          return null;
        }
    ).bind(continer);
```
