### ISSUE TITLE
[Feature-Request] Supporting exoplayer-ima

### ISSUE THREAD

**Issue by loicsiret** [eneim/kohii#99]
Hi,

is the support of ima in your backlog ?
If so, di you need some help for doing it ?

**Comment by eneim** [comment]
@loicsiret Hi, yes it is under design at the moment. One thing I really want to know is the real-world use cases/scenarios. What kind of behavior/use case you want to have with exoplayer-ima support. It will help me to make it done easier :D. Currently I barely follow the API of IMA and what ExoPlayer shows in the demo.

**Comment by loicsiret** [comment]
If you want, we can talk about it :)

Le mar. 25 août 2020 à 08:14, Nam Nguyen Hoai <notifications@github.com> a
écrit :

**Comment by loicsiret** [comment]
To follow
Currently, what I need is : 
 - be able to pass a adTagUrl to the video
 - provide custom imasdksettings (can be injected somewhere)
 - monitor adEvent callback

Right now in our application we have two kind of ads video : AdsOnly and Preroll.

I take some time looking in Toro library and it is exactly the same thing that I need. 😅

If I can help you to develop this part, don't hesitate to tell me how I can help you 😎

**Comment by eneim** [comment]
@loicsiret Oh sorry I could not reply to you earlier, was in a busy last week. I will push the code of my current design with the basic building blocks. I think you can take a look and explore the ability of it. 

Of course, PRs are always welcome. For any details that are business-related (which contains information you cannot disclose in github issue), you can email me at nam@ene.im for further discussion as well.

**Comment by eneim** [comment]
@loicsiret Hey, you can find the very first iteration of the design here: https://github.com/eneim/kohii/pull/100

As said, I have quite a little experience of Video Ads in practice. What I know is mostly from reading the document (of IMA for example). Having feedback or even contributions are really helpful. Thanks and appreciate your contribution.

**Comment by loicsiret** [comment]
It works very well 👍 

Just one concern about one thing.

In our case, we received from backend a list of object like : 

```
class VideoModel(
    val url: String,
    val thumbnail: String,
    val autoplay: Boolean,
    val showSeekbar: Boolean,
    val width: Int,
    val height: Int,
    val adTagUrl: String?
)
```

Our backend is in charge to put adTagUrl or not  So in your solution (execpt error on my side) it is mandatory to have an adTagUrl.

I tried something like : 
```
 fun setUp(url: String, adTagUrl: String?): Binder {
        if (adTagUrl == null) {
            return manilo.setUp(url)
        } else {
            return manilo.setUp(AdMediaItem(url.toUri(), adTagUrl.toUri())) {
            }
        }
    }
```

But I get ```java.lang.IllegalArgumentException: Failed requirement.
        at kohii.v1.ads.exoplayer.PlayerViewImaBridgeCreator.createBridge(PlayerViewImaBridgeCreator.kt:40)
        at kohii.v1.exoplayer.PlayerViewPlayableCreator.createPlayable(PlayerViewPlayableCreator.kt:78)```

So to get it works, I have made something a little weird as : 
```
class VideoEngineSelector(fragment: Fragment) {

    val kohii = Kohii[fragment]
    val kohiiManager: Manager = Kohii[fragment].register(fragment)

    val manilo = Manilo[fragment]
    val maniloManager = Manilo[fragment].register(fragment)

    fun addBucket(recyclerView: RecyclerView) {
        kohiiManager.addBucket(view = recyclerView)
        maniloManager.addBucket(view = recyclerView)
    }

    fun setUp(url: String, adTagUrl: String?): Binder {
        if (adTagUrl == null) {
            return kohii.setUp(url)
        } else {
            return manilo.setUp(AdMediaItem(url.toUri(), adTagUrl.toUri())) {
            }
        }
    }
}
```

My advice would to make adTagUrl as optional

**Comment by eneim** [comment]
Yeah makes sense. I will see if the idea that Manilo is just an extended version of Kohii that can support ad optionally.

**Comment by eneim** [comment]
@loicsiret I just push an update to the pull request. It allows nullable AdUri and will fallback to PlayerViewBridge when null.

**Comment by loicsiret** [comment]
Amazing, I will try it tomorrow !
